DROP TABLE MAHASISWA6
CREATE TABLE MAHASISWA6 (
  NIM NUMBER PRIMARY KEY,
  NAMA VARCHAR2(50),
  TGL_LAHIR DATE
);

SELECT * FROM MAHASISWA6;


DROP TABLE MATAKULIAH6
CREATE TABLE MATAKULIAH6 (
  KODE_MK VARCHAR2(10) PRIMARY KEY,
  NAMA_MK VARCHAR2(50),
  SKS NUMBER
);

SELECT * FROM MATAKULIAH6;

DROP TABLE NILAI6
CREATE TABLE NILAI6 (
  NIM NUMBER,
  KODE_MK VARCHAR2(10),
  NILAI CHAR(1),
  BOBOT NUMBER,
  PRIMARY KEY (NIM, KODE_MK)
);

SELECT * FROM NILAI6;


